Opensourcecontri/Hacktoberfest-2021

python/Most Stones Removed with Same Row or Column.py
Added Most Stones Removed with Same Row or Column using python and data structures
=> Create Most Stones Removed with Same Row or Column.py

python/Binary Search Tree to Greater Sum Tree.py
Added Binary Search Tree to Greater Sum Tree using python and data structures
=> Create Binary Search Tree to Greater Sum Tree.py

python/Maximum Depth of Binary Tree.py
Added Maximum Depth of Binary Tree using python
=> Create Maximum Depth of Binary Tree.py

python/Container With Most Water.py
Create Container With Most Water.py
=> Create Container With Most Water.py

Sudoku Solver
=> Sudoku Solver C++

Indian Coin Exchange
=> Indian Coin Exchange in C++

python/rock-paper-scissors-game.py
create a rock paper scissors game and add it to python folder.
=> create a rock paper scissors game and add it

javascript/script.js
I made this game using java script using function and arrays.
=> PigGame in java script

cpp/Rat in Maze
=> Rat in Maze - C++

cpp/N-Queen
=> N-Queen problem - C++

javascript/index.js
i made this game using java script
=> Guess my number game using java script

python/readEmail.py
simple python program to read and display emails
=> read and displays emails

cpp/LCS for 3 Strings
=> LCS for 3 Strings - C++

python/WordWrapProblem.py
The following Dynamic approach strictly follows the algorithm given in solution of Cormen book. First we compute costs of all possible lines in a 2D table lc[][]. The value lc[i][j] indicates the cost to put words from i to j in a single line where i and j are indexes of words in the input sequences. If a sequence of words from i to j cannot fit in a single line, then lc[i][j] is considered infinite (to avoid it from being a part of the solution). Once we have the lc[][] table constructed, we can calculate total cost using following recursive formula. In the following formula, C[j] is the optimized total cost for arranging words from 1 to j.
=> created WordWrapProblem.py

3sum.py, python/3sum.py
=> The 3sum problem solution is uploaded

python/Internet Speed Test - GUI
Python Code to find the Internet Speed Test
=> Internet Speed Test - GUI

cpp/bubble_sort.cpp
Bubble sort algorithm written in c++
=> add bubble sort algorithm in cpp

go/ispalindrom.go
add is palindrom number checker written in golang
=> add is palindrom number checker algorithm in go

python/Convert Sorted Array to Binary Search Tree.py
Added Convert Sorted Array to Binary Search Tree using python and data structures.
=> Create Convert Sorted Array to Binary Search Tree.py

java/threeSumProblem.java
The 3sum problem
Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.
Notice that the solution set must not contain duplicate triplets.
```
Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]
```
=> Solve the 3sum problem using Java

java/arrayList.java
The ArrayList class is a resizable array.  
I have implemented ArrayList class using a menu.
To know more about [ArrayList](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html)
=> ArrayList program using java uploaded

java/fibonacci.java
Calculating Fibonacci value using Dynamic Programming(Memoization)  in java.
=> Fibonacci using Dynamic Programming Java

cpp/Vectors_implementation.cpp
This PR adds implementation Of Vector in C++ STL
=> Added Vectors_implementation

python/Random forest Regression/Position_Salaries.csv, python/Random forest Regression/Untitled.ipynb
Salary prediction using the Random Forest Regression algorithm.
=> Random Forest Regression

python/Youtube-Gui-Video-Downloader.py
I am a beginner in programming and also beginner in opensource project. so can you review my code
=> Adding python youtube-gui

python/eliminate.py
Given the single linked list above function that removes the consecutive duplicate values, the given list only contains unique elements and returns the head to the updated list.
=> eliminate.py

python/chatbot.py
=> Added Chatbot!

cpp/Google KickStart 2020 Round H - Retype.cpp, cpp/caesarCipher.cpp
Adding two files program in C++ 
- Works both on upper case and lower case input
- Ignore symbols or char other than alphabet (do nothing)
- Custom cipher key input
- pass all (2) test case
=> Adding two files program in C++

python/factorial.py, python/prime.py
This program is for finding out factorials of a given number.
=> Adding files to Python Folder

python/keylogger.py
This program is able to store keystrokes made my user in a text file. In this case, the text file is named as mylog.txt and is saved in desktop.
=> Added Keylogger Program

python/SplitArray.py
Given an integer array A of size N, check if the input array can be splitted in two parts such that -
- Sum of both parts is equal
- All elements in the input, which are divisible by 5 should be in same group.
- All elements in the input, which are divisible by 3 (but not divisible by 5) should be in other group.
- Elements which are neither divisible by 5 nor by 3, can be put in any group.
=> SplitArray.py

python/Python User Login system(TechnoFrost27).py
Uses tkinter and local file storage, really easy
=> Python user login system

python/Password Generator(TechnoFrost27).py
A file that randomly generates a password
=> Added password generator 

python/sudoku.py
=> program to solve sudoku

java/Find Unique.java
=> Find Unique.java

cpp/add_complex_using_struc.cpp
Added code to add complex numbers using structures in CPP.
=> Add complex numbers using Structures in CPP

cpp/factorial_dp.cpp
factorial of a number with different time complexities using dp.
=> factorial of a number with different time complexities

cpp/graphImplementation.cpp
graph implementation using adjacency list
=> graph implementation

cpp/maxProfitDP.cpp
famous maxProfit problem of dynamic programming by selling the rod by cutting into parts
=> maxProfit dp problem

combining.py
Reverts Opensourcecontri/Hacktoberfest-2021#105
=> Revert "Create combining.py"

html/Calculator.html
=> Calculator.html

tic_tac_toe_game.cpp
C++ prog to play tic tac toe game.
=> TIC_TAC_TOE_GAME.CPP

javascript/brickBreakerGame/index.css, javascript/brickBreakerGame/index.html, javascript/brickBreakerGame/index.js
Brick breaker game has been added to the JS folder
=> Add brick breaker game in JavaScript folder

arduino/simpleArduinoStruct/simpleArduinoStruct.ino
Add Arduino Serial Simple Struct
=> Add Arduino Simple Struct

cpp/RoundRobin.cpp
Round Robin is a CPU scheduling algorithm where each process is assigned a fixed time slot in a cyclic way.
=> Round Robin Scheduling #hacktoberfest

cpp/Bit Manipulation/bit_manipulation.cpp
Added Bit Manipulation program in C++
=> Added Bit Manipulation program in C++

cpp/DSU.cpp
I have added cpp script which contains the DSU class with the following functionalities:
Please merge the this PR, if you think I did some useful.
Thank you :)
=> Disjoint set union cpp

cpp/sieve _of_eratosthenes.cpp
I have added the `Sieve of eratosthenes` code for CPP in the CPP folder.
-[X] I made a class for Sieve of eratosthenes, which takes a value which is the maximum value that can be occurred in the set.
-[X] Further, using `isPrime(int n)` function we can check that n is prime or not
-[X] We can also get all the primes less than n using primes(int n).
Please merge my PR, if you think it' relevant
Thank you :)
=> Sieve of eratosthenes code for CPP added.

reverse_k_nodes_alternatively.cpp
I have added the solution for the problem `Reverse k nodes alternatively in linked list`.
Please merge my PR, if you think it' relevant
Thank you :)
=> Added reverse k node alternatively in linked list.

python/Dictionary sum
=> Create Dictionary sum

python/Maximum and Minimum
=> Maximum and Minimum

java/italiandeck/ItalianCard.java, java/italiandeck/ItalianDeck.java
Added italian card game deck.
Closes: https://github.com/Opensourcecontri/Hacktoberfest-2021/issues/158
=> Hacktoberfest - ItalianCard

cpp/is_string_palindrome.cpp
I have added the C++ program for checking whether a given string is palindrome or not.
Happy Coding :)
=> Is String Palindrome program added.

cpp/is_Number_Palindrome.cpp
I have added the C++ program checking whether given number is palindrome or not.
=> Is Number Palindrome C++ program added.

cpp/Bit Manipulation/Powerof2.cpp
Power of 2 using Bit manipulation.
=> Powerof2.cpp

cpp/AddStarAtRepeated
add star at string when character are repeating.
=> AddStarAtRepeated

cpp/Bit Manipulation/subsets.cpp
=> subsets.cpp

cpp/Bit Manipulation/twoRepeatingTwice.cpp
Two element repeating twice in an array.
=> twoRepeatingTwice.cpp

cpp/radixSort.cpp
=> added radix sort code using bin/bucket sort

python/insertionsort.py
I have inserted a python program for insertion sort, Kindly accept it.
=> Added a insertion sort python file

cpp/Euclid.cpp
=> Euclid.cpp

cpp/Primefactor.cpp
Calculate prime factor in cpp.
=> Primefactor.cpp

cpp/sieve of eratosthenes.cpp
=> sieve of eratosthenes

cpp/ModuloArthmetics.cpp
=> ModuloArthmetics.cpp

cpp/Geometric Possibility (GEOPOS).cpp
Finding Geometric Possibility using cpp
=> Finding Geometric Possibility using cpp

cpp/MINNOTES.cpp
=> Solving GCD question

cpp/Cats and a Mouse.cpp
=> Cat and mouse game using cpp

python/Python Program for Find largest prime factor of a number.py
Added Python Program for largest prime factor of a number
=> Largest prime factor of a number.py

Http request in c++
=> Http request in c++

java/binaryTodecimal.java
I have added binary To decimal program in java
=> Added binary To decimal program in java

C-Language/HttpResquestInC.cpp
Simple C example of doing an HTTP POST
=> Simple C example of doing an HTTP POST
